import mysql.connector as sql
db=sql.connect(
host='localhost',
user='root',
password='rootroot',
database='airline_management_system')
cur=db.cursor()

cur.execute("CREATE TABLE USERS (USER_NAME VARCHAR(20), NAME_ VARCHAR(20),MOBILE_NUMBER DOUBLE, E_MAIL_ID VARCHAR(20),DATE_OF_BIRTH DATE,PASS_WORD INT)")
cur.execute("CREATE TABLE FLIGHTS (ORIGIN VARCHAR(20),DESTINATION VARCHAR(20), FLIGHT_DATE DATE, FLIGHT_TIME TIME,AIRLINES VARCHAR(20), FLIGHT_NUMBER INT)")
cur.execute("CREATE TABLE TICKET_BOOKING (PASSENGER_NAME VARCHAR(20),TICKET_ID INT, ORIGIN VARCHAR(20),DESTINATION VARCHAR(20), TRAVEL_DATE DATE,FLIGHT_NUMBER INT,SEAT_CLASS VARCHAR(15),SEAT_TYPE VARCHAR(15))")
cur.execute("CREATE TABLE COSTS (TICKET_ID INT PRIMARY KEY, TOTAL_COST INT)")
cur.execute("CREATE TABLE TRANSACTIONS_CARD (TICKET_ID INT, CARD_NUMBER BIGINT,NAME_ON_CARD VARCHAR(20),CVV_NUMBER INT, PIN_NUMBER INT)")
cur.execute("CREATE TABLE TRANSACTIONS_UPI (TICKET_ID INT, UPI_ID BIGINT, PIN_NUMBER INT)")
cur.execute("CREATE TABLE FOOD (TICKET_ID INT, FOOD VARCHAR(20),COUNT_ INT, COST INT)")
cur.execute("CREATE TABLE FLIGHT_DETAILS(FLIGHT_NUMBER INT PRIMARY KEY, AIRLINES_NAME VARCHAR(30), ORIGIN VARCHAR(30), DESTINATION VARCHAR(30), FLIGHT_DATE DATE, FLIGHT_TIME TIME,  PILOT_1_NAME VARCHAR(30),PILOT_1_ID VARCHAR(30), PILOT_1_EXPERIENCE VARCHAR(30), PILOT_2_NAME VARCHAR(30),PILOT_2_ID VARCHAR(30), PILOT_2_EXPERIENCE VARCHAR(30), SEATS INT);")
cur.execute("CREATE TABLE ADMINS(ADMIN_ID VARCHAR(20) PRIMARY KEY,PASS_WORD INT)")
cur.execute("CREATE TABLE STAFFS (STAFF_NAME VARCHAR(20),GENDER VARCHAR(1),MOBILE_NUMBER DOUBLE,ADDRESS VARCHAR(30),STAFF_ID INT)")
cur.execute("INSERT INTO ADMINS VALUES('AD1',2911)")
db.commit()
db.close()

